### ISSUE TITLE
Bug no output for okay torrents with deluged

### ISSUE THREAD

**Issue by forsomefun2** [JohnDoee/autotorrent#27]
I found a bug I believe
I thought it had to do with the new version and changes that occured in correcting the debugging
but it seems to be with deluged and the if a label already exist

Deluge
Found 1 torrent(s)
Traceback (most recent call last):
  File "autotorrent-env/bin/autotorrent", line 11, in <module>
    sys.exit(commandline_handler())
  File "/home/snickerpop/autotorrent/autotorrent-env/local/lib/python2.7/site-packages/autotorrent/cmd.py", line 210, in commandline_handler
    result = at.handle_torrentfile(os.path.join(current_path, torrent), dry_run)
  File "/home/snickerpop/autotorrent/autotorrent-env/local/lib/python2.7/site-packages/autotorrent/at.py", line 468, in handle_torrentfile
    if self.client.add_torrent(torrent, destination_path, files['files'], fast_resume):
  File "/home/snickerpop/autotorrent/autotorrent-env/local/lib/python2.7/site-packages/autotorrent/clients/deluge.py", line 151, in add_torrent
    self.rpcclient.call('label.add', self.label)
  File "/home/snickerpop/autotorrent/autotorrent-env/local/lib/python2.7/site-packages/deluge_client/client.py", line 214, in call
    return self._receive_response(self.deluge_version)
  File "/home/snickerpop/autotorrent/autotorrent-env/local/lib/python2.7/site-packages/deluge_client/client.py", line 193, in _receive_response
    raise exception(exception_msg)
deluge_client.client.WrappedException: Label already exists, Exception, Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/deluge-1.3.15-py2.7.egg/deluge/core/rpcserver.py", line 302, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/deluge/plugins/label/core.py", line 174, in add
    check_input(not (label_id in self.labels), _('Label already exists'))
  File "build/bdist.linux-x86_64/egg/deluge/plugins/label/core.py", line 68, in check_input
    raise Exception(message)
Exception: Label already exists

The program is still works 
but if your doing something like
2>> or just want to see from the commandline the okay torrents. They are all missing and it only has 
found torrent message, and nothing about which torrent was found

For now the fix seems to be removing the label as it is not needed for deluge to run.

**Comment by JohnDoee** [comment]
It's a bit embarrassing, because I actually did this correctly in my streaming plugin.

Fixed, thanks for reporting it.

**Comment by forsomefun2** [comment]
You closed the issue but I'm still seeing the same issue. 

Might just have to do with changes upcoming in deluge 2.0 Beta

**Comment by JohnDoee** [comment]
How new is your Deluge 2? They changed the RPC Protocol and there's an open pull request for that here https://github.com/JohnDoee/deluge-client/pull/29

If it's linux and newer than mid November, that might be it.

**Comment by forsomefun2** [comment]
Yeah it probably was around that time that I got it. I remember pulling the dev branch for install

**Comment by forsomefun2** [comment]
Not sure what that command did
but it fix the issue now as soon as I added the label plugin.
